### ISSUE TITLE
Small tricks in 'to_wav' function

### ISSUE THREAD

**Issue by ShengleiH** [andabi/music-source-separation#10]
`to_wav` function call the `get_stft_matrix` function, in which the magnitude is multiplied by np.exp(1.j * phases) - `magnitudes * np.exp(1.j * phases)`. Why you do this?

**Comment by andabi** [comment]
@ShengleiH The whole process to waveforms is (magnitude, phase) -> stft_matrix (spectrogram) -> waveforms. In the first conversion, we need that formula theoretically.
