### ISSUE TITLE
it's really not easy to reproduce the project ！

### ISSUE THREAD

**Issue by ucasiggcas** [andabi/music-source-separation#39]
Dear,

You project maybe good,
but no one has reproduced,
1.No ikala data
2.The data sets has no split into train/validataion/eval
3.No instruction about the config.py and how to modify it
4.No steps about the usage, I mean detail.

Thx

**Comment by ucasiggcas** [comment]
Who has got success please help me .
Who can help me will be grateful.
Who care me ?

**Comment by Tortoise17** [comment]
HI
@ ucasiggcas 
Did you get the iKala data?

**Comment by ucasiggcas** [comment]
> HI
> @ ucasiggcas
> Did you get the iKala data?

No, 
please use the mir-1k

**Comment by Tortoise17** [comment]
Send me your email.

**Comment by ucasiggcas** [comment]
> Send me your email.

ucas010@126.com

**Comment by cheriylan** [comment]
> Send me your email.

could you have ikala,can you send it to me

**Comment by ucasiggcas** [comment]
@cheriylan No
Now I have got success ,but the rp is not perfect for complex situation
Will close the issue
Bye
