### ISSUE TITLE
issue on eval.py

### ISSUE THREAD

**Issue by chesterkuo** [andabi/music-source-separation#5]
**Issue:** 
(music-source-separation.git) chester@chester-tw-ngs1-ubuntu1:/sdc1/git/music-source-separation$ python ./eval.py
Traceback (most recent call last):
  File "./eval.py", line 16, in <module>
    from mir_eval.separation import bss_eval_sources
ImportError: No module named mir_eval.separation

Fixed , we need to create a __init__.py with mir_eval folder , in this way , we don't need to export PYTHOPATH.

**Comment by andabi** [comment]
@chesterkuo updated. the init file was filtered by my wrong .gitingore usage. Thank you for the issue!
